trade_cal:
	python main.py --op=trade_cal

stock_list:
	python main.py --op=stock_list

daily:
	python main.py \
	--op=daily \
	--tscd='000001.SZ' \
	--st='20180101' \
	--ed='20180110'

daily_all:
	python main.py \
	--op=daily \
	--st='20180101' \
	--ed='20190306' \
	--all=true
